### ISSUE TITLE
Bug: webSocketConn 疑似缺失已读字节数累加

### ISSUE THREAD

**Issue by chinaerserver** [AlexStocks/getty#30]
connection.go中  func (w *gettyWSConn) recv() ([]byte, error){}方法内疑似缺失
atomic.AddUint32(&conn.readBytes, uint32(len(b))) 累加wsConn中对readBytes的计数

**Comment by AlexStocks** [comment]
@chinaerserver pls comment this pr https://github.com/AlexStocks/getty/pull/31 . If there is no comment/error from you, I will merge it 3 days later.
