### ISSUE TITLE
 Imp: using writev

### ISSUE THREAD

**Issue by AlexStocks** [AlexStocks/getty#33]
Before v1.12 the fd.Writev of golang have a [fatal bug](https://github.com/golang/go/pull/32138), 
so I send multiple byte steam packages by merging them. However, the latest golang version v1.14.1 has released, I think getty should use writev now.

there are two funcs which can use writev:

1 session.go:session.WriteBytesArray
2 session.go:session.handleLoop

**Comment by AlexStocks** [comment]
cc @watermelo

**Comment by watermelo** [comment]
received~

**Comment by watermelo** [comment]
`WriteBytesArray` without writev.
![image](https://user-images.githubusercontent.com/14182114/77630387-e619b780-6f85-11ea-94c4-16959c9d415d.png)

`WriteBytesArray` with writev.
![image](https://user-images.githubusercontent.com/14182114/77630430-faf64b00-6f85-11ea-89fe-999817ee34a9.png)

It seems to reduce syscall. @AlexStocks
