### ISSUE TITLE
getty可以用来做物联网modbus长连接网关吗，每个连接需要进行定时下发指令到设备

### ISSUE THREAD

**Issue by ZhangChengJi** [AlexStocks/getty#70]

**Comment by AlexStocks** [comment]
如果是处理 TCP 协议，应该是可以的。定时任务在 OnCron 里面执行。

**Comment by ZhangChengJi** [comment]
OnCron好像不可以，需要每个连接建立自己的定时任务，

**Comment by ZhangChengJi** [comment]
我现在是通过时间轮建立定时任务下发的task,然后存储到sync.map

**Comment by AlexStocks** [comment]
> OnCron好像不可以，需要每个连接建立自己的定时任务，

OnCron 确实是连接级别的，每个连接单独一个

**Comment by AlexStocks** [comment]
> 我现在是通过时间轮建立定时任务下发的task,然后存储到sync.map

有解决方法就好

**Comment by AlexStocks** [comment]
你能否来 https://github.com/AlexStocks/getty/issues/40 这里登记下？
