### ISSUE TITLE
服务端关闭连接时，客户端异常关闭

### ISSUE THREAD

**Issue by jayliao2025** [AlexStocks/getty#73]
**What happened**: 服务端主动关闭连接时，返回的错误码及错误信息异常
<img width="881" alt="image" src="https://github.com/AlexStocks/getty/assets/38313715/7a0e650f-235e-4297-8952-6a3aa32e51ea">
<img width="1014" alt="image" src="https://github.com/AlexStocks/getty/assets/38313715/ed14ebe4-a935-4199-b623-b18b8a27c738">

**What you expected to happen**:客户端得到正确的错误码和错误信息

**How to reproduce it (as minimally and precisely as possible)**: 使用master分支的代码，服务端主动关闭连接，100%出现

**Anything else we need to know?**:

**Comment by AlexStocks** [comment]
@Jardaliao thank you for your contribution. I have merge your pr and draft a new release v1.3.2.

What's more, I hope you can submit a ut for your PR. 

And please attention that :
![image](https://github.com/AlexStocks/getty/assets/7959374/76594f61-fb9a-4b01-a301-22e2b9cec928)

```go
if code < 1000 || code > 1015 {
  return fmt.Errorf("invalid close code: %d", code)
 }
```
